Repository googleapis/java-workflow-executions, pull requests merged in 2021-08, with the labels that each got.

#152 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: workflowexecutions, context: full

#162 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: workflowexecutions

#159 feat!: release gapic-generator-java v2.0.0
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionsClient.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionsSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/ExecutionsStubSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/GrpcExecutionsStub.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1beta/ExecutionsClient.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1beta/ExecutionsSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1beta/stub/ExecutionsStubSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1beta/stub/GrpcExecutionsStub.java
  synth.metadata
Labels: cla: yes, api: workflowexecutions, context: full

#168 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: automerge, kokoro:force-run, cla: yes, api: workflowexecutions, context: full

#175 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: workflowexecutions
