Repository googleapis/java-workflow-executions, pull requests merged in 2021-09, with the labels that each got.

#177 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: workflowexecutions, context: full

#169 chore: update gapic-generator-java version to 2.1.0
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/ExecutionsStubSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1beta/stub/ExecutionsStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, api: workflowexecutions, context: full

#182 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, api: workflowexecutions, context: full

#183 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, kokoro:force-run, cla: yes, api: workflowexecutions, context: full

#184 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  owlbot.py
  synth.py
Labels: automerge, cla: yes, api: workflowexecutions

#190 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: workflowexecutions

#200 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: workflowexecutions

#207 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: workflowexecutions

#196 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: workflowexecutions
