Repository googleapis/java-workflow-executions, pull requests merged in 2021-06, with the labels that each got.

#124 chore: release gapic-generator-java v1.0.10
  google-cloud-workflow-executions/src/test/java/com/google/cloud/workflows/executions/v1/ExecutionsClientTest.java
  google-cloud-workflow-executions/src/test/java/com/google/cloud/workflows/executions/v1beta/ExecutionsClientTest.java
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#131 chore: release gapic-generator-java v1.0.12
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/ExecutionsStubSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1beta/stub/ExecutionsStubSettings.java
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#132 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#135 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: workflowexecutions, automerge, cla: yes

#134 chore: release gapic-generator-java v1.0.13
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionName.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/WorkflowName.java
  proto-google-cloud-workflow-executions-v1beta/src/main/java/com/google/cloud/workflows/executions/v1beta/ExecutionName.java
  proto-google-cloud-workflow-executions-v1beta/src/main/java/com/google/cloud/workflows/executions/v1beta/WorkflowName.java
  synth.metadata
Labels: api: workflowexecutions, cla: yes, context: full
