Repository googleapis/java-workflow-executions, pull requests merged in 2021-07, with the labels that each got.

#139 chore: minimize noise from build scripts
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: partial

#144 chore: remove distributionManagement section
  pom.xml
Labels: api: workflowexecutions, automerge, cla: yes

#146 chore: remove distributionManagement section
  google-cloud-workflow-executions-bom/pom.xml
Labels: api: workflowexecutions, automerge, cla: yes

#145 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#148 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#149 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#153 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: workflowexecutions, automerge, cla: yes

#154 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: workflowexecutions, automerge, cla: yes
