Repository googleapis/java-workflow-executions, pull requests merged in 2021-05, with the labels that each got.

#106 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: workflowexecutions, automerge, cla: yes

#107 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: none

#111 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#108 chore: fix scm links
  pom.xml
Labels: api: workflowexecutions, cla: yes

#112 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#114 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#116 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full

#119 feat: add v1 client
  .repo-metadata.json
  google-cloud-workflow-executions-bom/pom.xml
  google-cloud-workflow-executions/pom.xml
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionsClient.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionsSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/gapic_metadata.json
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/package-info.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/ExecutionsStub.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/ExecutionsStubSettings.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/GrpcExecutionsCallableFactory.java
  google-cloud-workflow-executions/src/main/java/com/google/cloud/workflows/executions/v1/stub/GrpcExecutionsStub.java
  google-cloud-workflow-executions/src/test/java/com/google/cloud/workflows/executions/v1/ExecutionsClientTest.java
  google-cloud-workflow-executions/src/test/java/com/google/cloud/workflows/executions/v1/MockExecutions.java
  google-cloud-workflow-executions/src/test/java/com/google/cloud/workflows/executions/v1/MockExecutionsImpl.java
  grpc-google-cloud-workflow-executions-v1/pom.xml
  grpc-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionsGrpc.java
  pom.xml
  proto-google-cloud-workflow-executions-v1/clirr-ignored-differences.xml
  proto-google-cloud-workflow-executions-v1/pom.xml
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/CancelExecutionRequest.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/CancelExecutionRequestOrBuilder.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/CreateExecutionRequest.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/CreateExecutionRequestOrBuilder.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/Execution.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionName.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionOrBuilder.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionView.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ExecutionsProto.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/GetExecutionRequest.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/GetExecutionRequestOrBuilder.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ListExecutionsRequest.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ListExecutionsRequestOrBuilder.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ListExecutionsResponse.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/ListExecutionsResponseOrBuilder.java
  proto-google-cloud-workflow-executions-v1/src/main/java/com/google/cloud/workflows/executions/v1/WorkflowName.java
  proto-google-cloud-workflow-executions-v1/src/main/proto/google/cloud/workflows/executions/v1/executions.proto
  proto-google-cloud-workflow-executions-v1beta/clirr-ignored-differences.xml
  synth.metadata
  synth.py
  versions.txt
Labels: api: workflowexecutions, automerge, cla: yes

#123 chore: update README
  README.md
Labels: api: workflowexecutions, automerge, cla: yes

#121 chore: start tracking obsolete files
  synth.metadata
Labels: api: workflowexecutions, automerge, cla: yes, context: full
