Repository googleapis/java-workflow-executions, pull requests merged in 2022-01, with the labels that each got.

#246 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: api: workflowexecutions, owlbot:ignore

#250 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: workflowexecutions, owlbot:ignore

#252 chore: add codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: workflowexecutions
